module.exports = {
  apps: [
    {
      name: 'api',
      cwd: '/home/runner/my_project/apps/api',
      script: 'node_modules/.bin/ts-node',
      args: '--transpile-only src/main.ts',
      interpreter: 'none',
      env: { NODE_ENV: 'development', API_PORT: '3001' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'web',
      cwd: '/home/runner/my_project/apps/web',
      script: 'npx',
      args: 'next dev -p 3002',
      interpreter: 'none',
      env: { NODE_ENV: 'development' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'proxy',
      cwd: '/home/runner/my_project',
      script: 'node',
      args: 'proxy.mjs',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 1000,
    },
  ],
};
