packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  unrs-resolver: true

overrides:
  multer: ^2.2.0
  lodash: ^4.17.24
  qs: ^6.15.2
  file-type: ^21.3.2
